name: Auto destroy

on:
  schedule:
    - cron: "00 24 * * *"  
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  destroy-release:
    if: ${{ 
      github.event_name == 'schedule' ||
      (github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[CLEANUP]')) ||
      github.event_name == 'workflow_dispatch'
      }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
          
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          
      - name: Terraform Init
        run: terraform init -backend-config=env/backend.tfvars

      - name: Check if Composer environment exists
        run: |
          if gcloud composer environments describe demo-lab --location europe-west1; then
            echo "Environment exists, proceeding to destroy"
          else
            echo "Environment does not exist, skipping destroy"
            exit 0
          fi

      - name: Wait 5 minutes before destroy
        run: sleep 300

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file env/project.tfvars
